name: 'Code Quality'

on:
  pull_request:
    branches: ['main']

jobs:
  #eslint:
  #    name: Eslint
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Check out Code
  #        uses: actions/checkout@v2
  #      - name: Install NodeJS
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version-file: .nvmrc
  #          cache: npm
  #      - name: Install Dependencies
  #        run: npm i
  #      - name: Lint it
  #        run: npm lint
  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install Dependencies
        run: npm i
      - name: Check for Typescript errors
        run: npm run typecheck
